proconnect-gouv/federation

- back/apps/bridge-http-proxy/src/controllers/bridge-http-proxy.controller.ts
- back/apps/bridge-http-proxy/src/enums/bridge-http-proxy-routes.enum.ts
- back/apps/bridge-http-proxy/src/services/bridge-http-proxy.service.ts
- back/apps/csmr-http-proxy/src/controllers/csmr-http-proxy.controller.ts
Concerne uniquement la hybridge
Ajout de point d'API `/livez` qui peuvent être utilisés comme LivenessProbe par Kube ou comme healthcheck par Docker Compose (la nomenclature `/livez` reprend celle proposée par Kube https://kubernetes.io/docs/reference/using-api/health-checks/)
Au sein des messages traités par l'hybridge, on assume également que le `X-Forwarded-Proto` est du HTTPS par défaut lorsque celui-ci n'est pas défini (suite à proposition d'Acton)
> feat(hybridge): add liveness probes

- docker/bash/commands/docker.sh
- docker/bash/commands/up.sh
- docker/builds/node/Dockerfile
- docker/compose/fca-low/core-rie.yml
- docker/compose/fca-low/core.yml
- docker/compose/fca-low/exploitation-fca-low.yml
- docker/compose/fca-low/hybridge.yml
- docker/compose/fca-low/mocks.yml
- docker/compose/shared/shared.yml
This PR replaces the use of the `ghcr.io/proconnect-gouv/federation/nodejs:v22.13.0-dev` (copied from `registry.gitlab.dev-franceconnect.fr/france-connect/fc/nodejs:v22.13.0-dev`) with locally-built image based on the official NodeJS Docker image.
This avoids a dependency on a custom Docker registry, and also automatically builds an image that is compatible with the local platform (i.e. `arm64` on Apple Silicon laptops).
> Stop using published custom NodeJS image

- docker/bash/config.sh
Restore env var removed in previous clean of some dks task relatives files.
This vars are usefull for getting the path of the file with the last logs allowing to check if admin is running.
> [PCF-633]🔨 Restore missing last dks logs env var

- docker/bash/utils/commands.sh
When only writing dks, the default behaviour is to start the default stack.
You can still write
```sh
dks switch medium
```
Or simply:
```sh
dks
```
> [PCF-689]🔨 Shortcut for starting default stack with dks

- back/libs/account-fca/src/services/account-fca.service.spec.ts
- back/libs/account-fca/src/services/account-fca.service.ts
- quality/fca/cypress/integration/usager/connexion-sub.feature
- quality/fca/cypress/support/usager/steps/service-provider-steps.ts
Correct the following problem:
```js
db.accountFca.insertOne({
active: true,
idpIdentityKeys: [{ idpSub: "<A>", idpUid: "Curasso" }],
sub: 1,
});
db.accountFca.insertOne({
active: true,
idpIdentityKeys: [
{ idpSub: "<A>", idpUid: "MonComptePro" },
{ idpSub: "<B>", idpUid: "Curasso" },
],
sub: 2,
});
db.accountFca.find({
"idpIdentityKeys.idpSub": "<A>",
"idpIdentityKeys.idpUid": "Curasso",
});
```
The last request returns the two accounts.
> [PCF-696]🗃 Correct and optimize accountFca fetch

- docker/bash/utils/commands.sh
Since #79 typing `docker-stack` (or `dks`) by itself restarts a complete stack (does a `docker-stack switch medium`).
Consensus seems to be that this is not very friendly to new users who are unfamiliar with `docker-stack` and would prefer to be shown the command list. It is sometimes appropriate for a program to have a default action when invoked without arguments (see `ls`, `yarn`) but it is not applicable to every program. I submit that this is only appropriate when the default action has no persistent effects (as with `ls`) or it is idempotent (as with `yarn`).
Make `docker-stack` print the command list when not given a command.
> Make docker-stack print help when no command is given

- .github/workflows/ci-tests.yml
The latest GitHub Actions runner image includes Docker Compose 2.32.0, which fails to build required images for dependent services.
Add a step to upgrade Docker Compose to the latest version, which does not have this bug.
Note that the replaced step that ran two `export` commands had no effect since variables exported in a shell one step are not persistent for subsequent steps (you have to append them to `$GITHUB_ENV`).
> Upgrade Docker Compose to fix CI

- .github/workflows/labeler.yml
Added `issues: write` permission to the labeler workflow to fix the "You do not have permission to create labels" error.
> 🔧 ci(labeler): add issues write permission to fix label creation

- back/libs/oidc-provider/src/dto/oidc-provider-config.dto.ts
- back/libs/oidc-provider/src/services/oidc-provider-config.service.spec.ts
- back/libs/oidc-provider/src/services/oidc-provider-config.service.ts
pairwiseIdentifier is used when resolving pairwise ID Token and Userinfo sub claim values. We do not use pairwise ID in ProConnect but only public ones.
> 🔥 remove unused oidc provider conf

- back/apps/core-fca/src/controllers/data-provider.controller.ts
- back/libs/oidc-provider/src/oidc-provider.controller.ts
In a debug session, we found out that not having the url called and no context on these logs make them hard to use.
I propose to add both until we found out what to do with these logs.
> 🔊 debug logs are more usable

- docker/bash/commands/node.sh
- docker/docker-stack
This command helps clean the Node.js stack by removing node_modules folders and built JavaScript files. It is particularly helpful when working with the Admin which is composed of multiple apps:
- the parent admin app
- shared
- fc-exploitation
Each of these apps has its own node_modules folder.
> 🔨 Add a dks command for cleaning node modules and dist

- admin/deploy/pm2/app.json
The admin container no longer starts in production.
```
2025-08-21T11:17:29: PM2 log: Launching in no daemon mode
2025-08-21T11:17:29: PM2 error: Error: Script not found: /var/www/app/dist/src/main.js
```
> 🚑 Build admin container with correct path

- docker/bash/commands/up.sh
- docker/compose/fca-low/core-rie.yml
- docker/compose/fca-low/core.yml
- docker/compose/fca-low/exploitation-fca-low.yml
- docker/compose/fca-low/hybridge.yml
- docker/compose/fca-low/mocks.yml
This should avoid the need for explicit startup of rp-all in docker-stack.
> Make services depend on rp-all

- admin/Dockerfile
- back/Dockerfile
- docker/compose/fca-low/admin.yml
- docker/compose/fca-low/hybridge.yml
- docker/compose/shared/shared.yml
Using the existing NESTJS_INSTANCE environment
variable lets all those containers share a command defined in the common Dockerfile.
> ♻️ Remove command override from Compose services

- docker/README.md
- docker/bash/commands/docker.sh
- docker/bash/commands/node.sh
- docker/bash/config.sh
- docker/compose/fca-low/admin.yml
- docker/compose/fca-low/core.yml
- docker/compose/fca-low/hybridge.yml
- docker/compose/fca-low/mocks.yml
- docker/compose/fca-low/mongo.yml
- docker/compose/shared/shared.yml
From https://github.com/proconnect-gouv/federation/commits?author=jonathanperret
Replace environment variables with relative paths in Compose files This makes the Compose stack more self-contained, less dependent on the `docker-stack` wrapper.
Note that `_clean_pc_dist` in `node.sh` was the last user of `VOLUMES_DIR` but was itself unused so I removed it, along with its `_detect_instances` and `_get_env` dependencies.
> 🚚 Replace environment variables with relative paths in Compose files

- compose.yaml
- docker/bash/config.sh
This removes the need to set `COMPOSE_PROJECT_NAME` and `COMPOSE_FILE` in `docker-stack`, but also lets plain `docker compose` work (as long as the `CURRENT_UID` variable is set, currently).
> Add root compose.yaml file

- admin/cypress.config.js
- admin/cypress/plugins/otp-plugin.js
- admin/src/config/totp.ts
- quality/fca/cypress/plugins/otp-plugin.ts
Relevant RFC: https://datatracker.ietf.org/doc/html/rfc6238#section-5.2
The TOTP RFC recommends using 'an acceptable OTP transmission delay window' of at most one. Zero is too tight for practical purposes and leads to wasted time waiting for the next TOTP token to appear when using an authenticator app.
In addition, we have two mitigations for this problem in Cypress: originally the environment variable TOTP_WINDOW was set to "loose" to allow this one-step delay. However, this could not possibly have worked, since this variable is only ever seen by the Cypress testing environment, which *generates* OTP codes, and could not have any effect on the admin application which *accepts* OTP codes - and the 'window' config only affects acceptance.
Because this was ineffective a second mitigation …
> 🔒️(totp) use RFC-compliant OTP window and simplify testing

- admin/Dockerfile
- back/.dockerignore
- back/Dockerfile
- docker/bash/commands/node.sh
- docker/compose/fca-low/admin.yml
- docker/compose/fca-low/hybridge.yml
- docker/compose/shared/shared.yml
- docker/docker-stack
The previous setup of:
volumes:
- '../../../back:/var/www/app'
- '/var/www/app/node_modules'
Meant that `/var/www/app/node_modules` was first shadowed by the bind mount of `back`, then "re-introduced" as an anonymous volume whose contents were automatically copied from the image (see
https://docs.docker.com/engine/storage/volumes/#mounting-a-volume-over-existing-data).
This unnecessarily duplicated the entire `node_modules` directory into as many anonymous volumes as there were containers, and also took several seconds at container creation.Also, since Docker Compose will preserve anonymous volumes by default, it was easy to end up in a situation where the underlying image was rebuilt with new `node_modules` content that was not picked up (as the anonymous volumes contained previous …
> Use node_modules from node image directly instead of copying to an anonymous volume

- admin/cypress/integration/identity-provider/identity-provider-update.spec.js
- quality/fca/cypress/integration/exploitation/creation-modification-fi.feature
- quality/fca/cypress/support/exploitation/steps/exploit-idp-form-steps.ts
Moves these two admin tests from `quality/fca`, translated into Cypress specs rather than BDD features, to `admin`
> Move and translate admin tests introduced for empty default siret

- back/apps/core-fca-low/src/controllers/interaction.controller.spec.ts
- back/apps/core-fca-low/src/controllers/interaction.controller.ts
- quality/fca/cypress/integration/usager/connexion-session.feature
We are not sure why the session was duplicated.
It seems intended as a session key rotation to mitigate cookie theft attacks, but the previous key does not appear to be revoked.
Such protection is relevant when elevating privileges within a session or when revoking a session using the same key, but that's not the case in the authorize endpoint. It still applies in the callback endpoint.
This duplication would cause issues when refactoring the prompt to matche the Panva API.
I propose removing it now to make the code clrearer.
> ♻️  remove session duplication in authorize

- docker/bash/commands/mongo.sh
This lets one execute MongoDB queries without going through an interactive shell, for example:
```bash
$ docker-stack mongo --quiet --eval 'db.getCollectionNames()' 2>/dev/null
[
"accountFca",
"client",
"fqdnToProvider",
"notifications",
"provider",
"scopes"
]
```
```bash
$ docker-stack mongo --quiet --eval 'JSON.stringify(db.client.find().toArray())' 2>/dev/null | jq
[
{
"_id": {
"$oid": "68dd4517f1318620d076c8fa"
},
"name": "FSA - FSA1-LOW",
"title": "FSA - FSA1-LOW Title",
"redirect_uris": [
"https://fsa1-low.docker.dev-franceconnect.fr/oidc-callback"
],
"post_logout_redirect_uris": [
"https://fsa1-low.docker.dev-franceconnect.fr/"
],
"client_secret": "+sqGL4XE6aqzIMOp/DKC1jWB8I+8qE1jW6iz2tUv8lt+ZZzxjyoCBQeuAcJTFZxfLywkn6cAICK5JPLxYM0+8pk/q7CGHUfr/gzr3ZYRroWWE+egEEDxqRYDYe0=",
"key": …
```
> 🧑‍💻 Let `docker-stack mongo` accept arguments

- docker/bash/utils/commands.sh
Arguments to `docker-stack` commands like `docker-stack compose` or `docker-stack mongo` can be arbitrarily complex and require quoting. Currently, these arguments are expanded then broken up again by the `_command_run` function in `commands.sh`, resulting in the following undesirable behaviour:
```bash
$ docker-stack compose exec core echo "hello          world"
hello world
$ docker-stack compose exec core printf "%s\n" "hello world" "bye world"
hello
world
bye
world
```
Using quotes around `"$@"` (or variants like `"${@:2}"` [causes Bash to properly keep the arguments as separated by the caller](https://www.gnu.org/software/bash/manual/bash.html#index-_0040), instead of expanding them and re-splitting words on whitespace.
```bash
$ docker-stack compose exec core echo "hello …
```
> 🧑‍💻 Do not break `docker-stack` command arguments

- docker/bash/commands/docker.sh
- docker/docker-stack
This is the list of the remaining commands today:
```
_command_register "reset-pg" "_hook_admin" "Init postgres Admin"
### Mongo
_command_register "reset-db-core-fca-low" "_reset_db_core_fca_low" ""             # Description to be defined # Deprecated
_command_register "reset-db" "_reset_db_core_fca_low" "Alias to reset-db-core-fca-low" # Backward compatibility entry
_command_register "reset-mongo" "_reset_mongodb" "reset-mongo <mongo-service-name> : Reset given mongodb container"
_command_register "reset-mongo-as-prod" "_reset_mongodb_as_prod" "reset-mongo-as-prod <mongo-service-name> : Reset given mongodb container with production IDPs"
_command_register "mongo" "_mongo_core_shell" "Open mongo shell for core"
## Nodejs apps
_command_register "stop" "_stop" "stop application" …
```
> ⚰ Remove dead commands from dks

- docker/compose/shared/shared.yml
The squid container takes a long time to shut down.
Set its `stop_signal` to `SIGKILL`. There is no reason to wait for a graceful shutdown as the container is essentially stateless.
> 👷 faster dks switch
